/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LogRouteImport } from './routes/log'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ExercisesIndexRouteImport } from './routes/exercises/index'
import { Route as ExercisesExerciseIdRouteImport } from './routes/exercises/$exerciseId'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions/$sessionId'
import { Route as WorkoutIndexRouteImport } from './routes/workout/index'
import { Route as WorkoutDateRouteImport } from './routes/workout/$date'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesIndexRoute = ExercisesIndexRouteImport.update({
  id: '/exercises/',
  path: '/exercises/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesExerciseIdRoute = ExercisesExerciseIdRouteImport.update({
  id: '/exercises/$exerciseId',
  path: '/exercises/$exerciseId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutIndexRoute = WorkoutIndexRouteImport.update({
  id: '/workout/',
  path: '/workout/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutDateRoute = WorkoutDateRouteImport.update({
  id: '/workout/$date',
  path: '/workout/$date',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/log': typeof LogRoute
  '/settings': typeof SettingsRoute
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/workout/$date': typeof WorkoutDateRoute
  '/exercises/': typeof ExercisesIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/workout/': typeof WorkoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/log': typeof LogRoute
  '/settings': typeof SettingsRoute
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/workout/$date': typeof WorkoutDateRoute
  '/exercises': typeof ExercisesIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/workout': typeof WorkoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/log': typeof LogRoute
  '/settings': typeof SettingsRoute
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/workout/$date': typeof WorkoutDateRoute
  '/exercises/': typeof ExercisesIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/workout/': typeof WorkoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/log'
    | '/settings'
    | '/exercises/$exerciseId'
    | '/sessions/$sessionId'
    | '/workout/$date'
    | '/exercises/'
    | '/sessions/'
    | '/workout/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/log'
    | '/settings'
    | '/exercises/$exerciseId'
    | '/sessions/$sessionId'
    | '/workout/$date'
    | '/exercises'
    | '/sessions'
    | '/workout'
  id:
    | '__root__'
    | '/'
    | '/log'
    | '/settings'
    | '/exercises/$exerciseId'
    | '/sessions/$sessionId'
    | '/workout/$date'
    | '/exercises/'
    | '/sessions/'
    | '/workout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LogRoute: typeof LogRoute
  SettingsRoute: typeof SettingsRoute
  ExercisesExerciseIdRoute: typeof ExercisesExerciseIdRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  WorkoutDateRoute: typeof WorkoutDateRoute
  ExercisesIndexRoute: typeof ExercisesIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  WorkoutIndexRoute: typeof WorkoutIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/': {
      id: '/exercises/'
      path: '/exercises'
      fullPath: '/exercises/'
      preLoaderRoute: typeof ExercisesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/$exerciseId': {
      id: '/exercises/$exerciseId'
      path: '/exercises/$exerciseId'
      fullPath: '/exercises/$exerciseId'
      preLoaderRoute: typeof ExercisesExerciseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/': {
      id: '/workout/'
      path: '/workout'
      fullPath: '/workout/'
      preLoaderRoute: typeof WorkoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/$date': {
      id: '/workout/$date'
      path: '/workout/$date'
      fullPath: '/workout/$date'
      preLoaderRoute: typeof WorkoutDateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LogRoute: LogRoute,
  SettingsRoute: SettingsRoute,
  ExercisesExerciseIdRoute: ExercisesExerciseIdRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  WorkoutDateRoute: WorkoutDateRoute,
  ExercisesIndexRoute: ExercisesIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  WorkoutIndexRoute: WorkoutIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
