import { createTheme } from "@mantine/core";

import {
  ExtendedActionIcon,
  ExtendedAvatar,
  ExtendedButton,
  ExtendedCard,
  ExtendedCheckbox,
  ExtendedColorPicker,
  ExtendedDateInput,
  ExtendedDatePickerInput,
  ExtendedDateTimePicker,
  ExtendedMenu,
  ExtendedModal,
  ExtendedMultiSelect,
  ExtendedNotification,
  ExtendedPasswordInput,
  ExtendedPinInput,
  ExtendedPopover,
  ExtendedSelect,
  ExtendedNumberInput,
  ExtendedTextInput,
  ExtendedTimeInput,
  ExtendedTextarea,
} from "./components/extended/index";

const theme = createTheme({
  fontFamily: '"Manrope", sans-serif',
  headings: { fontFamily: '"Manrope", sans-serif' },
  primaryColor: "primary",
  primaryShade: 6,
  colors: {
    primary: [
      "#eff6ff",
      "#dbeafe",
      "#bfdbfe",
      "#93c5fd",
      "#60a5fa",
      "#3b82f6",
      "#2563eb",
      "#1d4ed8",
      "#1e40af",
      "#1e3a8a",
    ],
  },
  components: {
    Button: ExtendedButton,
    TextInput: ExtendedTextInput,
    NumberInput: ExtendedNumberInput,
    DateInput: ExtendedDateInput,
    PasswordInput: ExtendedPasswordInput,
    Card: ExtendedCard,
    ColorPicker: ExtendedColorPicker,
    Select: ExtendedSelect,
    DateTimePicker: ExtendedDateTimePicker,
    Notification: ExtendedNotification,
    Avatar: ExtendedAvatar,
    ActionIcon: ExtendedActionIcon,
    PinInput: ExtendedPinInput,
    DatePickerInput: ExtendedDatePickerInput,
    Checkbox: ExtendedCheckbox,
    Modal: ExtendedModal,
    Menu: ExtendedMenu,
    MultiSelect: ExtendedMultiSelect,
    Popover: ExtendedPopover,
    TimeInput: ExtendedTimeInput,
    Textarea: ExtendedTextarea,
  },
});

export default theme;
